ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: agentragio.local
      paths:
        - path: /
          pathType: Prefix
          component: frontend
          port: 80
        - path: /api
          pathType: Prefix
          component: backend
          port: 8000
  # tls:
  #   - hosts:
  #       - agentragio.local
  #     secretName: agentragio-tls